### ISSUE TITLE
SIGPIPE

### ISSUE THREAD

**Issue by ghost** [PerfectlySoft/Perfect-Net#3]
I was playing with EventSource from HTML5 with Perfect library, and got this signal. Everything seems to be working if I ignore it, but it's annoying because it forces debugger break.

It's possible that I'm doing some unsupported stuff. Anyway, this code in `initPipe` seems to work:

```
var set = Int32(1);
setsockopt(fd.fd, SOL_SOCKET, SO_NOSIGPIPE, &set, UInt32(sizeof(Int32.self)));
```

My understanding is that ignoring is is not a problem, since error will  be returned during write, but maybe I'm wrong.

**Comment by kjessup** [comment]
Interesting. We do ignore sigpipe for the process as a whole but that doesn't stop lldb from breaking unless you `process handle SIGPIPE -n true -p true -s false`.

I'll confirm if this stops it for good.

**Comment by kjessup** [comment]
Works great! Thank you very much.
